parameters:
#    sumerge_attendance.example.class: Sumerge\AttendanceBundle\Example

services:
#    sumerge_attendance.example:
#        class: %sumerge_attendance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
